[package]
name = "toasty-driver-mysql"
version = "0.11.0"
description = "MySQL driver for Toasty"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
categories.workspace = true
readme.workspace = true
documentation = "https://docs.rs/toasty-driver-mysql"

[features]
default = ["rustls"]
native-tls = ["sqlx-core/_tls-native-tls"]
rustls = ["sqlx-core/_tls-rustls-ring-webpki"]
rust_decimal = ["dep:rust_decimal", "toasty-core/rust_decimal", "toasty-sql/rust_decimal"]
bigdecimal = ["dep:bigdecimal", "toasty-core/bigdecimal", "toasty-sql/bigdecimal"]
jiff = ["dep:jiff", "toasty-core/jiff", "toasty-sql/jiff"]
net = ["toasty-core/net", "toasty-sql/net"]

[dependencies]
async-trait.workspace = true
toasty-core.workspace = true
toasty-sql.workspace = true
rust_decimal = { workspace = true, optional = true }
bigdecimal = { workspace = true, optional = true }
jiff = { workspace = true, optional = true }
sqlx-core.workspace = true
sqlx-mysql.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
