[package]
name = "toasty"
version = "0.11.0"
description = "An async ORM for Rust supporting SQL and NoSQL databases"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
categories.workspace = true
readme.workspace = true
documentation = "https://docs.rs/toasty"

[features]
default = ["rustls"]
dynamodb = ["dep:toasty-driver-dynamodb"]
migration = ["dep:serde", "dep:toml", "dep:toml_edit", "toasty-core/migration"]
mysql = ["dep:toasty-driver-mysql"]
native-tls = ["toasty-driver-mysql?/native-tls"]
postgresql = ["dep:toasty-driver-postgresql"]
rustls = ["toasty-driver-mysql?/rustls"]
sqlite = ["dep:toasty-driver-sqlite"]
turso = ["dep:toasty-driver-turso"]
rust_decimal = [
	"dep:rust_decimal",
	"toasty-core/rust_decimal",
	"toasty-driver-postgresql?/rust_decimal",
	"toasty-driver-mysql?/rust_decimal",
	"toasty-driver-sqlite?/rust_decimal",
	"toasty-driver-turso?/rust_decimal",
]
bigdecimal = [
	"dep:bigdecimal",
	"toasty-core/bigdecimal",
	"toasty-driver-postgresql?/bigdecimal",
	"toasty-driver-mysql?/bigdecimal",
	"toasty-driver-sqlite?/bigdecimal",
	"toasty-driver-turso?/bigdecimal",
]
jiff = [
	"dep:jiff",
	"toasty-core/jiff",
	"toasty-driver-postgresql?/jiff",
	"toasty-driver-mysql?/jiff",
	"toasty-driver-sqlite?/jiff",
	"toasty-driver-turso?/jiff",
]
net = [
	"toasty-core/net",
	"toasty-driver-postgresql?/net",
	"toasty-driver-mysql?/net",
	"toasty-driver-sqlite?/net",
	"toasty-driver-turso?/net",
]
serde = ["dep:serde_core", "dep:serde_json"]

[dependencies]
async-trait.workspace = true
toasty-macros.workspace = true
toasty-core.workspace = true

# Built-in database drivers
toasty-driver-dynamodb = { workspace = true, optional = true }
toasty-driver-mysql = { workspace = true, optional = true }
toasty-driver-postgresql = { workspace = true, optional = true }
toasty-driver-sqlite = { workspace = true, optional = true }
toasty-driver-turso = { workspace = true, optional = true }
serde_core = { version = "1.0.228", optional = true }
serde_json = { workspace = true, optional = true }

bit-set.workspace = true
by_address.workspace = true
hashbrown.workspace = true
rust_decimal = { workspace = true, optional = true }
bigdecimal = { workspace = true, optional = true }
deadpool.workspace = true
jiff = { workspace = true, optional = true }
tokio-stream.workspace = true
uuid.workspace = true
indexmap.workspace = true
index_vec.workspace = true
inventory.workspace = true
serde = { workspace = true, optional = true }
tokio.workspace = true
toml = { workspace = true, optional = true }
toml_edit = { workspace = true, features = ["serde"], optional = true }
tracing.workspace = true

[dev-dependencies]
assert-struct.workspace = true
proptest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
toasty-driver-sqlite = { workspace = true }

[lints]
workspace = true
